### ISSUE TITLE
團員申請加入，團主確認

### ISSUE THREAD

**Issue by zizyzhang** [zizyzhang/Onigiri#10]
團員申請加入，團主確認，MsaageBox的实现

**Comment by ChouWei** [comment]
麻煩prototype

**Comment by zizyzhang** [comment]
右上角MessageBox按钮

**Comment by ChouWei** [comment]
要怎麼抓到這團裡的所有成員?

**Comment by ChouWei** [comment]
是不是在"我的訂單"還有個待批准的畫面<-

**Comment by zizyzhang** [comment]
已經傳給前端了

**Comment by ChouWei** [comment]
有關開group的都要改吧(現在是只要確認跟團就會加入資料庫，如果增加團主確認的功能，勢必會增加if的判斷是否已經批準)吧...有點複雜耶..有甚麼好主意嗎?

**Comment by zizyzhang** [comment]
order加狀態就行了，

发自我的 iPhone

**Comment by ChouWei** [comment]
已經有個付款狀態了，要分開還是重新取名?0.0

**Comment by zizyzhang** [comment]
用同一個
发自我的 iPhone

**Comment by ChouWei** [comment]
messagebox 在"我發起的團購"右上角嗎?

**Comment by zizyzhang** [comment]
對

发自我的 iPhone

**Comment by ChouWei** [comment]
要用POPOVER還是普通的跳轉頁面還是像facebook的Message一樣?

**Comment by zizyzhang** [comment]
普通页面

Sent from Mail Master
在2016年07月11日 17:03，ChouWeimailto:notifications@github.com 写道:

要用POPOVER還是普通的跳轉頁面還是像facebook的Message一樣?

**Comment by ChouWei** [comment]
團主mail通知給團員改成用Line去分享訊息出去OK嗎?

**Comment by zizyzhang** [comment]
这个没有问题的话我关闭了。
