### ISSUE TITLE
備註按鈕

### ISSUE THREAD

**Issue by zizyzhang** [zizyzhang/Onigiri#12]
留言按鈕

**Comment by ChouWei** [comment]
麻煩prototype

**Comment by zizyzhang** [comment]
资料库->多一个留言，

**Comment by ChouWei** [comment]
Order 要有"確認跟團"才有資料，第一個人輸入沒辦法把"備註"加進去..

**Comment by zizyzhang** [comment]
就是這樣啊，還有我覺得加在grpmember更好

发自我的 iPhone

**Comment by ChouWei** [comment]
OK，已改成GROUP_MEMBER了。但現在有個問題，一定要先"確認跟團"後才能把"備註"的內容傳到資料庫=.=

**Comment by ChouWei** [comment]
確認跟團後才有GROUP_MEMBER的產生，才能塞comment資料...卡在流程問題..

**Comment by zizyzhang** [comment]
難道在沒點餐之前就和商家說加辣嗎，這個流程不對在哪裡

发自我的 iPhone

**Comment by ChouWei** [comment]
下了備註，然後按了返回不跟團，那不就多一筆GROUP_MEMBER了@@

是不是應該先知道訂餐定了什麼，才下備註呢?0.0
![image](https://cloud.githubusercontent.com/assets/13924048/16544478/5eab358a-413a-11e6-989a-87be568a4736.png)

**Comment by ChouWei** [comment]
[C:\Users\hsiang1\Desktop](url)

**Comment by zizyzhang** [comment]
當然是確認的時候才把備註訊息傳給伺服器

发自我的 iPhone

**Comment by ChouWei** [comment]
OK，已搞定@@

**Comment by ChouWei** [comment]
備註最後要在哪裡呈現?

**Comment by zizyzhang** [comment]
我发起的团购

Sent from Mail Master
在2016年07月12日 13:11，ChouWeimailto:notifications@github.com 写道:

備註最後要呈現在哪裡?

**Comment by ChouWei** [comment]
已完成
