### ISSUE TITLE
 團的上限金額(4h)

### ISSUE THREAD

**Issue by zizyzhang** [zizyzhang/Onigiri#13]
團的上限金額(4h)

**Comment by DongShanHu** [comment]
4h是什麼意思??
\

**Comment by zizyzhang** [comment]
我要做4小时的意思

**Comment by zizyzhang** [comment]
我开始做了？

**Comment by tion846** [comment]
團的上限金額 跟[ 團員申請加入，團主確認](https://github.com/zizyzhang/Onigiri/issues/14) 有衝突:
若團主批准了，但是超過團的上限金額，那訂單要如何?
