### ISSUE TITLE
郵件開團通知

### ISSUE THREAD

**Issue by zizyzhang** [zizyzhang/Onigiri#14]
郵件開團通知

**Comment by ChouWei** [comment]
麻煩prototype

**Comment by zizyzhang** [comment]
关注团主

**Comment by ChouWei** [comment]
關注團主在哪個頁面...(討論亂想結果:搜尋團員html->團員詳細資料html 裏頭的某一個位置 的 "關注團主")?
還是先做一個btn來寄mail來看?

**Comment by ChouWei** [comment]
哈囉，有個好主意嗎?

**Comment by tion846** [comment]
可以使用 [Nodemailer ](https://github.com/nodemailer/nodemailer)這個插件嗎?
還是有別的更好的方式?

**Comment by ChouWei** [comment]
團主發郵件要寄給誰...?目前沒有好友機制..

**Comment by DongShanHu** [comment]
私人團開啟就有了， 寄給目前他想季的好友八

**Comment by tion846** [comment]
不是還有關注團主?

**Comment by ChouWei** [comment]
.....  所以意思是先做私人團或關注團主囉..

**Comment by ChouWei** [comment]
團主mail通知給團員改成用Line去分享訊息出去OK嗎?

**Comment by zizyzhang** [comment]
這個issue的進度是什麼，在哪個branch

**Comment by DongShanHu** [comment]
一樣在testLine 裡面，有開團郵件通知 跟拒絕時郵件通知，
乃文那時是直接commit起來 沒有新建分之

**Comment by zizyzhang** [comment]
好的， 從`dev` checkout新分支后繼續做。

**Comment by zizyzhang** [comment]
先不做 關注團主，先做推送被團主接受或拒絕
