### ISSUE TITLE
取消訂單

### ISSUE THREAD

**Issue by DongShanHu** [zizyzhang/Onigiri#17]

**Comment by zizyzhang** [comment]
描述一下使用案例

**Comment by DongShanHu** [comment]
使用案例名稱 :取消訂單
使用案例描述 :使用者可對訂單進行編輯刪除功能

主要參與者 :使用者
前置條件: 存在一筆以上(含)的訂單
主要情節: 參與者             系統回應
1.使用者進行取消訂單  1-1刪除該筆訂單

後置條件
刪除完畢確認資料庫已對該筆訂單做刪除
例外情節
1.團已達外送金額
2.開團失敗

**Comment by zizyzhang** [comment]
在订单明细中增加取消订单按钮

**Comment by zizyzhang** [comment]
完成
