### ISSUE TITLE
必須作確認誰已經繳錢了 (我發起的團購)

### ISSUE THREAD

**Issue by zizyzhang** [zizyzhang/Onigiri#9]
必須作確認誰已經繳錢了 (我發起的團購)

**Comment by tion846** [comment]
確認付款畫面要新增一個html?還是放在哪個html裡?

**Comment by zizyzhang** [comment]
我开的团

**Comment by zizyzhang** [comment]
![](http://i.imgur.com/K4u4ome.png)

**Comment by tion846** [comment]
難以排版...
是否需要增加ordStatus來表示付款狀態?
usrId要怎麼換成usrName在template顯示?

**Comment by zizyzhang** [comment]
usrid就是usrname
排版自己嘗試
要加狀態沒錯

**Comment by DongShanHu** [comment]
ORDER資料表裡面沒有usrname ，要在直接在DB裡面新增 還是慢慢找

**Comment by zizyzhang** [comment]
就是usrId
发自我的 iPhone

**Comment by tion846** [comment]
![image](https://cloud.githubusercontent.com/assets/14860723/16544086/570b46cc-412a-11e6-8950-e1e219052b47.png)

usrId 是數字...

同一個usrid買兩樣東西時，會分成兩個ordId...這有點不好迴圈，也不好一次修改ordStatus

**Comment by zizyzhang** [comment]
那應該就是usrName吧。可能要改server回傳的類別吧，記得excel要先改

发自我的 iPhone

**Comment by tion846** [comment]
![image](https://cloud.githubusercontent.com/assets/14860723/16544896/ff979494-4148-11e6-88d8-8ec86f793000.png)
![image](https://cloud.githubusercontent.com/assets/14860723/16544902/30a66268-4149-11e6-9335-07e432c81333.png)
教我怎麼排版....orders的資料不知道怎麼{{#each}}

**Comment by zizyzhang** [comment]
這個有點麻煩，你先研究吧，我回去再說

发自我的 iPhone

**Comment by zizyzhang** [comment]
就当做完成了吧。。
